"""Change line items

Revision ID: 5720ed99bb19
Revises: 6a0dbff2c69e
Create Date: 2025-08-28 11:57:57.930720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5720ed99bb19'
down_revision: Union[str, Sequence[str], None] = '6a0dbff2c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('transaction_value', sa.Float(), nullable=False))
    op.alter_column('line_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line_items', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('line_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('line_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('line_items', 'discount')
    op.drop_column('line_items', 'tax_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('line_items', sa.Column('discount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('line_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('line_items', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('line_items', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('line_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('line_items', 'transaction_value')
    # ### end Alembic commands ###
